### ISSUE TITLE
ECX Follow-up

### ISSUE THREAD

**Issue by KeneNwogu** [oree-xx/Tax#1]
Hello, you submitted this repository as your favourite project. It's great work, but you didn't send your contact details on the form. I would love to talk about the project. If you are still up for it, can you send your email as a comment to this issue

Regards,
Kenechukwu.
Development Lead, ECX 5.0.

**Comment by oree-xx** [comment]
ohh okay.
oreoluwaoluwasina@gmail.com

**Comment by KeneNwogu** [comment]
Thank you for the swift reply. Regards.
